[{
    "login": "ashrafmo-1",
    "id": 124946844,
    "node_id": "U_kgDOB3KJnA",
    "avatar_url": "https://avatars.githubusercontent.com/u/124946844?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ashrafmo-1",
    "html_url": "https://github.com/ashrafmo-1",
    "followers_url": "https://api.github.com/users/ashrafmo-1/followers",
    "following_url": "https://api.github.com/users/ashrafmo-1/following{/other_user}",
    "gists_url": "https://api.github.com/users/ashrafmo-1/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ashrafmo-1/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ashrafmo-1/subscriptions",
    "organizations_url": "https://api.github.com/users/ashrafmo-1/orgs",
    "repos_url": "https://api.github.com/users/ashrafmo-1/repos",
    "events_url": "https://api.github.com/users/ashrafmo-1/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ashrafmo-1/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Ashraf Mohamed",
    "company": "egypt",
    "blog": "https://ashrafmo-1.web.app/",
    "location": "Damietta",
    "email": null,
    "hireable": null,
    "bio": "Front End Devloper ",
    "twitter_username": null,
    "public_repos": 19,
    "public_gists": 0,
    "followers": 2,
    "following": 1,
    "created_at": "2023-02-10T01:43:39Z",
    "updated_at": "2023-06-14T15:38:34Z"
}]